apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: oma-certs-ufe
spec:
  module-uri: http://oma-certs-ufe.wac-hospital/build/oma-wac-certs.esm.js
                     # module web komponentu pre tento mikroFE
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: oma-ambulance-certs-app    # element, ktorý bude vložený na stránku
                                    # pri navigácii na zoznam čakajúcich
      attributes:
        - name: api-base
          value: http://localhost:30082/api
      path: oma-certs      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: "[oma] Správca kurzov a certifikácií"      # názov mikro aplikácie
      details: Spravuje aktuálne certifikácie a kurzy absolvované zamestnancami nemocnice
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti
                                    # musí byť táto hodnota nastavená na true
  hash-suffix: v1alpha1             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
                                    # sa mení názov URL pre modul a tým je možné predísť problémom
                                    # s verziami vo vyrovnávacích pamätiach
