apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
 name: oma-gitops-repo # v spoločnom klastri je nasadených viacero takýchto objektov
 namespace: wac-hospital
spec:
 interval: 1m0s
 ref:
     branch: master
 timeout: 1m0s
 url: https://github.com/oma-wac-cv/wac-ambulance-gitops

   # secretRef:
   # name: oma-repository-pat
