apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
 name: oma-gitops-repo # v spoločnom klastri je nasadených viacero takýchto objektov
 namespace: wac-hospital
spec:
 interval: 1m0s
 ref:
     branch: main
 timeout: 1m0s
 url: https://github.com/oma-wac-cv/wac-ambulance-gitops

# ak používate privátny repozitár nezabudnite doplniť autentifikačné údaje
# secretRef:
#    name: oma-repository-pat
