apiVersion: apps/v1
kind: Deployment
metadata:
  name: oma-ambulance-certs-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /oma-openapi-certs
            - name: BASE_URL
              value: /oma-openapi-certs-ui