apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: slkd/ambulance-ufe
  newName: slkd/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: master.20240304.1414 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
- name: slkd/ambulance-wl-webapi
  newName: slkd/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: master.20240325.1423 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
- name: slkd/ambulance-certs-ufe
  newName: slkd/ambulance-certs-ufe # {"$imagepolicy":  "wac-hospital:ambulance-certs-ufe:name"}
  newTag: master # {"$imagepolicy": "wac-hospital:ambulance-certs-ufe:tag"}
- name: slkd/ambulance-certs-webapi
  newName: slkd/ambulance-certs-webapi # {"$imagepolicy":  "wac-hospital:ambulance-certs-webapi:name"}
  newTag: master # {"$imagepolicy": "wac-hospital:ambulance-certs-webapi:tag"}