apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital  # chceme tieto objekty umiestniť do `wac-hospital` namespace
                         # tento zapis preťaží hodnoty "namespace" vo všetkých objektoch


commonLabels:
  app.kubernetes.io/part-of: wac-hospital

resources:
- ../../../apps/oma-ambulance-ufe
- ../../../apps/oma-certs-ufe
- ../../../apps/oma-ambulance-webapi

components:
 - ../../../components/version-developers
 - https://github.com/oma-wac-cv/wac-ambulance-webapi//deployments/kustomize/components/mongodb

patches:
- path: patches/ambulance-webapi.service.yaml
- path: patches/mongodb-auth.secret.yaml
